name: Deploy to Server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.GROSESTEST }}  # Приватный ключ для доступа к серверу

      - name: Deploy via rsync
        run: |
          rsync -avz --delete --exclude='.git/' \
            -e "ssh -o StrictHostKeyChecking=no" \
            ./ golg0fa@212.115.110.215:/var/www/golgofa.bar/